version: "3"
services:
  db:
    image: mongo:4.2.11
    volumes:
      - mongodb:/data/db
  client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    depends_on: 
      - db
      - server
  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
volumes:
  mongodb: {}
